In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
import numpy as np
import open3d as o3d
from rlbench.action_modes.action_mode import MoveArmThenGripper
from rlbench.action_modes.arm_action_modes import JointVelocity
from rlbench.action_modes.gripper_action_modes import Discrete
from rlbench.environment import Environment
from rlbench.tasks import ReachTarget

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
action_mode = MoveArmThenGripper(
  arm_action_mode=JointVelocity(),
  gripper_action_mode=Discrete()
)
env = Environment(action_mode, headless=False)
env.launch()

task = env.get_task(ReachTarget)
descriptions, obs = task.reset()
obs, reward, terminate = task.step(np.random.normal(size=env.action_shape))

In [5]:
task._scene._workspace.get_bounding_box()

[-0.32499998807907104,
 0.32499998807907104,
 -0.45500004291534424,
 0.45500004291534424,
 -0.0,
 0.0]

In [2]:
import sys
sys.path.append('..')

from src.rlbench.voxel_grid import VoxelGrid
from src.rlbench.action_mode import ActionMode
from src.rlbench.enviroment import RLBenchEnv

In [3]:
lb = np.array([-0.3, -0.5, 0.6])
ub = np.array([0.7, 0.5, 1.6])
N = 10
env = RLBenchEnv('ReachTarget', (lb, ub), N)
ts = env.reset()

In [5]:
env.step(np.array([7,7,7]))

> /home/khromykhla/Documents/github/perciever/src/rlbench/action_mode.py(34)action()
     32         arm = np.concatenate([arm, DOWN_QUAT], -1)
     33         self.arm_action_mode.action(scene, arm)
---> 34         self.gripper_action_mode.action(scene, grip)
     35 
     36     def action_shape(self, scene: Scene) -> tuple[int, ...]:



ipdb>  c


Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/home/khromykhla/Apps/anaconda3/envs/perceiver/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_29400/1332536423.py", line 1, in <module>
    env.step(np.array([7,7,7]))
  File "/home/khromykhla/Documents/github/perciever/notebooks/../src/rlbench/enviroment.py", line 39, in step
    obs, reward, terminate = self.task.step(action)
  File "/home/khromykhla/Apps/anaconda3/envs/perceiver/lib/python3.10/site-packages/rlbench/task_environment.py", line 99, in step
    self._action_mode.action(self._scene, action)
  File "/home/khromykhla/Documents/github/perciever/notebooks/../src/rlbench/action_mode.py", line 35, in action
  File "/home/khromykhla/Apps/anaconda3/envs/perceiver/lib/python3.10/site-packages/rlbench/action_modes/gripper_action_modes.py", line 60, in action
    assert_action_shape(action, self.action_shape(scene.robot))
  

In [5]:
scene = env.task._scene

In [6]:
dir(scene)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_cam_front',
 '_cam_front_mask',
 '_cam_over_shoulder_left',
 '_cam_over_shoulder_left_mask',
 '_cam_over_shoulder_right',
 '_cam_over_shoulder_right_mask',
 '_cam_overhead',
 '_cam_overhead_mask',
 '_cam_wrist',
 '_cam_wrist_mask',
 '_demo_record_step',
 '_get_misc',
 '_has_init_episode',
 '_has_init_task',
 '_initial_robot_state',
 '_initial_task_pose',
 '_initial_task_state',
 '_obs_config',
 '_place_task',
 '_robot_shapes',
 '_set_camera_properties',
 '_start_arm_joint_pos',
 '_starting_gripper_joint_pos',
 '_step_callback',
 '_variation_index',
 '_workspace',
 '_workspace_boundary',
 '_workspace_maxx',
 '_workspace_

In [13]:
action = np.array([5,5,5,5])

In [14]:
ts  = env.step(action)

> /home/khromykhla/Documents/github/perciever/src/rlbench/action_mode.py(30)action()
     28     def action(self, scene: Scene, action: Array) -> None:
     29         import pdb; pdb.set_trace()
---> 30         action = np.take_along_axis(self._actgrid, action[np.newaxis], 0)
     31         arm, grip = np.split(action.squeeze(0), [3])
     32         arm = np.concatenate([arm, DOWN_QUAT], -1)



ipdb>  action


array([5, 5, 5, 5])


ipdb>  n


> /home/khromykhla/Documents/github/perciever/src/rlbench/action_mode.py(31)action()
     29         import pdb; pdb.set_trace()
     30         action = np.take_along_axis(self._actgrid, action[np.newaxis], 0)
---> 31         arm, grip = np.split(action.squeeze(0), [3])
     32         arm = np.concatenate([arm, DOWN_QUAT], -1)
     33         self.arm_action_mode.action(scene, arm)



ipdb>  action


array([[0.02222222, 0.02222222, 0.02222222, 0.02222222]])


ipdb>  action /= 100
ipdb>  action


array([[0.00022222, 0.00022222, 0.00022222, 0.00022222]])


ipdb>  n


> /home/khromykhla/Documents/github/perciever/src/rlbench/action_mode.py(32)action()
     30         action = np.take_along_axis(self._actgrid, action[np.newaxis], 0)
     31         arm, grip = np.split(action.squeeze(0), [3])
---> 32         arm = np.concatenate([arm, DOWN_QUAT], -1)
     33         self.arm_action_mode.action(scene, arm)
     34         self.gripper_action_mode.action(scene, grip)



ipdb>  n


> /home/khromykhla/Documents/github/perciever/src/rlbench/action_mode.py(33)action()
     31         arm, grip = np.split(action.squeeze(0), [3])
     32         arm = np.concatenate([arm, DOWN_QUAT], -1)
---> 33         self.arm_action_mode.action(scene, arm)
     34         self.gripper_action_mode.action(scene, grip)
     35 



ipdb>  arm


array([2.22222222e-04, 2.22222222e-04, 2.22222222e-04, 0.00000000e+00,
       7.07106780e-01, 7.07106780e-01, 0.00000000e+00])


ipdb>  n


rlbench.backend.exceptions.InvalidActionError: A path could not be found because the target is outside of workspace.
> /home/khromykhla/Documents/github/perciever/src/rlbench/action_mode.py(33)action()
     31         arm, grip = np.split(action.squeeze(0), [3])
     32         arm = np.concatenate([arm, DOWN_QUAT], -1)
---> 33         self.arm_action_mode.action(scene, arm)
     34         self.gripper_action_mode.action(scene, grip)
     35 



ipdb>  obs


*** NameError: name 'obs' is not defined


ipdb>  qw


*** NameError: name 'qw' is not defined


ipdb>  c


InvalidActionError: A path could not be found because the target is outside of workspace.

In [5]:
scene = env.task._scene

In [7]:
dir(scene)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_cam_front',
 '_cam_front_mask',
 '_cam_over_shoulder_left',
 '_cam_over_shoulder_left_mask',
 '_cam_over_shoulder_right',
 '_cam_over_shoulder_right_mask',
 '_cam_overhead',
 '_cam_overhead_mask',
 '_cam_wrist',
 '_cam_wrist_mask',
 '_demo_record_step',
 '_get_misc',
 '_has_init_episode',
 '_has_init_task',
 '_initial_robot_state',
 '_initial_task_pose',
 '_initial_task_state',
 '_obs_config',
 '_place_task',
 '_robot_shapes',
 '_set_camera_properties',
 '_start_arm_joint_pos',
 '_starting_gripper_joint_pos',
 '_step_callback',
 '_variation_index',
 '_workspace',
 '_workspace_boundary',
 '_workspace_maxx',
 '_workspace_

In [10]:
bv = scene._workspace_boundary

In [13]:
dir(sc

['MAX_SAMPLES',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_boundaries',
 '_probabilities',
 'clear',
 'sample']